import express from 'express';
import dotenv from 'dotenv';
import { apiRouter } from './routers';
import cors from 'cors';
import knexConfig from './config/database';
import { Model } from 'objection';
import knex from 'knex';
dotenv.config();
Model.knex(knex(knexConfig));
const port = process.env.PORT || 9999;
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.set('view engine', 'ejs');
app.use(express.static('public'));
app.use('/api/v1', apiRouter);
app.listen(port, () => {
  console.log(`Server started at http://localhost:${port}`);
});
